//#ENJOY
/**

░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░ ░▒▓███████▓▒░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░░▒▓██████▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░      ░▒▓█▓▒░▒▓█▓▒░ 
 ░▒▓█████████████▓▒░░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░ 
                                                      

**/

const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "";
global.video = "";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "wasixml@gmail.com";
global.location = "Lahore,Pakistan.";
global.mongodb = process.env.MONGODB_URI || "";
global.allowJids = process.env.ALLOW_JID || "923192173398@s.whatsapp.net";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github = process.env.GITHUB || "https://github.com/Itxxwasi/WASI-MD-V2";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029VaDK8ZUDjiOhwFS1cP2j";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/1f4e6e1cc2ed1662adb36.jpg";
global.devs = "923135673658";
global.sudo = process.env.SUDO || "923192173398";
global.owner = process.env.OWNER_NUMBER || "923192173398";
global.style = process.env.STYLE || "3";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "true";
global.userImages = process.env.USER_IMAGES || "";
global.waPresence = process.env.WAPRESENCE || "recording";
global.readcmds = process.env.READ_COMMAND || "false";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "true";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";
global.autoreaction = process.env.autoreaction || "true";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://pair-qr-wasi-md.onrender.com";

global.SESSION_ID =
  process.env.SESSION_ID ||
  "SUHAIL_12_13_07_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICAxNzgsXG4gICAgICAgIDQsXG4gICAgICAgIDc2LFxuICAgICAgICAyNyxcbiAgICAgICAgMTUwLFxuICAgICAgICA1LFxuICAgICAgICAzNSxcbiAgICAgICAgMjMxLFxuICAgICAgICA0NCxcbiAgICAgICAgNjQsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNzcsXG4gICAgICAgIDQwLFxuICAgICAgICAxMjYsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTc4LFxuICAgICAgICA2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNixcbiAgICAgICAgOTUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMzksXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTU5LFxuICAgICAgICA2MyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxOTQsXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDMsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjIzLFxuICAgICAgICAxLFxuICAgICAgICAzOSxcbiAgICAgICAgNzEsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTg2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDk1LFxuICAgICAgICA3MCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxOTQsXG4gICAgICAgIDIzLFxuICAgICAgICAxODYsXG4gICAgICAgIDkzLFxuICAgICAgICA2NSxcbiAgICAgICAgNzQsXG4gICAgICAgIDEsXG4gICAgICAgIDE4NixcbiAgICAgICAgODMsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTQ0LFxuICAgICAgICA4MixcbiAgICAgICAgMjU0LFxuICAgICAgICAxMDUsXG4gICAgICAgIDg5LFxuICAgICAgICAxOTcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTcyLFxuICAgICAgICAxLFxuICAgICAgICAxMTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIxNixcbiAgICAgICAgNzksXG4gICAgICAgIDUsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxNDksXG4gICAgICAgIDQ2LFxuICAgICAgICA1NixcbiAgICAgICAgMTkzLFxuICAgICAgICA3MCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNzYsXG4gICAgICAgIDgsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxOTksXG4gICAgICAgIDgzLFxuICAgICAgICAxNzIsXG4gICAgICAgIDY3LFxuICAgICAgICAzMyxcbiAgICAgICAgMjQyLFxuICAgICAgICA2NixcbiAgICAgICAgMTM3LFxuICAgICAgICAxNzksXG4gICAgICAgIDE5NCxcbiAgICAgICAgMzUsXG4gICAgICAgIDM5LFxuICAgICAgICA0OSxcbiAgICAgICAgODAsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjgsXG4gICAgICAgIDk2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3MSxcbiAgICAgICAgMzMsXG4gICAgICAgIDU3LFxuICAgICAgICAxOCxcbiAgICAgICAgODgsXG4gICAgICAgIDE2MSxcbiAgICAgICAgNjMsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjQwLFxuICAgICAgICAyMTQsXG4gICAgICAgIDk0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTE0LFxuICAgICAgICA0NSxcbiAgICAgICAgMTIzLFxuICAgICAgICA4OCxcbiAgICAgICAgNzYsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjA3LFxuICAgICAgICA0MyxcbiAgICAgICAgMTI3LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMjcsXG4gICAgICAgIDI5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDksXG4gICAgICAgIDQyLFxuICAgICAgICA0MixcbiAgICAgICAgMTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMixcbiAgICAgICAgMTU2LFxuICAgICAgICAxNDcsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjM2LFxuICAgICAgICAxMzEsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMzAsXG4gICAgICAgIDExNixcbiAgICAgICAgMjI4LFxuICAgICAgICAxNzQsXG4gICAgICAgIDIyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMCxcbiAgICAgICAgNDEsXG4gICAgICAgIDExMSxcbiAgICAgICAgODUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMzEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTY3LFxuICAgICAgICA0LFxuICAgICAgICAxNjYsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjIwLFxuICAgICAgICAyNDIsXG4gICAgICAgIDIxLFxuICAgICAgICAxNzEsXG4gICAgICAgIDExNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTMsXG4gICAgICAgIDIzNCxcbiAgICAgICAgODIsXG4gICAgICAgIDUzLFxuICAgICAgICA0MCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTg4LFxuICAgICAgICAxNzMsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNjQsXG4gICAgICAgIDE5NSxcbiAgICAgICAgNzAsXG4gICAgICAgIDIyMixcbiAgICAgICAgMzUsXG4gICAgICAgIDk0LFxuICAgICAgICA2NixcbiAgICAgICAgMTIzLFxuICAgICAgICAxNDUsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxODQsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjcsXG4gICAgICAgIDg3LFxuICAgICAgICAxMzIsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDI0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDgxXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAzMVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDMzLFxuICAgICAgICAxNSxcbiAgICAgICAgMzksXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjIsXG4gICAgICAgIDIxNixcbiAgICAgICAgNyxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDI5LFxuICAgICAgICAxMCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxMDYsXG4gICAgICAgIDcxLFxuICAgICAgICAxNzYsXG4gICAgICAgIDQ2LFxuICAgICAgICA1MCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMjIsXG4gICAgICAgIDEzMixcbiAgICAgICAgNCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNjIsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMixcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMTUsXG4gICAgICAgIDIzOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDksXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxMjgsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNjgsXG4gICAgICAgIDIxLFxuICAgICAgICAzNyxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMDYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjExLFxuICAgICAgICAxOTcsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTI5LFxuICAgICAgICAxMDIsXG4gICAgICAgIDE5LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE3MixcbiAgICAgICAgMSxcbiAgICAgICAgMTQyLFxuICAgICAgICAxLFxuICAgICAgICAyMzUsXG4gICAgICAgIDU4LFxuICAgICAgICAxODYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNzcsXG4gICAgICAgIDc4LFxuICAgICAgICAyMzksXG4gICAgICAgIDM4LFxuICAgICAgICAxMzNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEzMCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJwQmdYSEpKeklOK1Z0aEJ5emVMVnl1bXVUVFhSSHM2V05CSWhRaDNQem0wPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCI3OUJVRDE4a1NzS1dqWUhfSE9fZ2x3XCIsXG4gIFwicGhvbmVJZFwiOiBcIjBiZjFhMTM3LWI1Y2ItNDQ5Mi1hNjg2LTViZjQ3ODc4MjkyM1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNDAsXG4gICAgICAyMzYsXG4gICAgICAyMzQsXG4gICAgICAxOTIsXG4gICAgICAxNzUsXG4gICAgICAyMSxcbiAgICAgIDE3MCxcbiAgICAgIDEyNixcbiAgICAgIDEyMCxcbiAgICAgIDcsXG4gICAgICA1MSxcbiAgICAgIDIyMyxcbiAgICAgIDE3MCxcbiAgICAgIDc5LFxuICAgICAgMTA2LFxuICAgICAgNyxcbiAgICAgIDI2LFxuICAgICAgMjIxLFxuICAgICAgMTc4LFxuICAgICAgNDBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNixcbiAgICAgIDIwNCxcbiAgICAgIDI0NixcbiAgICAgIDU4LFxuICAgICAgMTE0LFxuICAgICAgNDksXG4gICAgICAxOTcsXG4gICAgICAyNDAsXG4gICAgICAxMTcsXG4gICAgICA2NSxcbiAgICAgIDEzMCxcbiAgICAgIDE1MSxcbiAgICAgIDIxNCxcbiAgICAgIDk3LFxuICAgICAgMTE4LFxuICAgICAgMTc5LFxuICAgICAgMjAzLFxuICAgICAgMTg5LFxuICAgICAgMTM1LFxuICAgICAgMTY3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjMxTVZFSkRBXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5NDc3MjU1NjMwNDoyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyNDM1NTUxOTcwMTgxNDY6MkBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNJdlNscWNCRU5mR243UUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlVnbVBEWHRzcFFXS0R0dEc2aE9sR3NtL1ZnV3czT2syZWpWRU5JY0toQ3c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiK0tuS0NGMzhERXg1NXlBOUpOQlRMVXZTdGg5Tzdod2cvQnhEUW1QKzIxc2FxZk1RTmdwbVQvWmZrMzFud0dtRkZQVEN6NDNjTElSRWJyM05yZEdJREE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwicUVKL2hVZWtlbW1KMlFDOS92dGNxaWw4MWpUM0ZiM3RFVUZ0L1hsR3M1MEl2SDFKMVhTNURXVzN5dHczSGpqM2hMYm9nZzBKZnZNZldFejJ2UFFNaGc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTQ3NzI1NTYzMDQ6MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA0NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwMTgxNTk1LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBUEQwXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFQRDAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ6WVZFTEtHcHVTMTR5Zjg3M1Byb1FNeER2UEVuZ3NNbjgxQ3FreCtCVkZzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM1MDU5NTMzOCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9"
module.exports = {
  menu: process.env.MENU || "",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.0.0",
  caption: process.env.CAPTION || "𝐅𝐈𝐋𝐄-𝐆𝐄𝐍𝐄𝐑𝐀𝐓𝐄𝐃-𝐁𝐘-𝐖𝐀𝐒𝐈-𝐌𝐃-𝐕2😍",
  author: process.env.PACK_AUTHER || "WASO",
  packname: process.env.PACK_NAME || "♥️",
  botname: process.env.BOT_NAME || "𝐖𝐀𝐒𝐈-𝐌𝐃-𝐕2",
  ownername: process.env.OWNER_NAME || "WASI",
  errorChat: process.env.ERROR_CHAT || "923192173398",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "",
  antilink_values: process.env.ANTILINK_VALUES || "chat.whatsapp.com",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  AUTOREACTION: process.env.AUTOREACTION || process.env.AUTOREACTION || "true",
  LANG: (process.env.THEME || "WASI").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
